org: farkmarnum
app: thaas
service: api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'} 

functions:
  api:
    handler: backend/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-domain-manager
  - serverless-frontend-plugin
  - serverless-hooks

custom:
  customDomain:
    domainName: api.thaas.io
    stage: ${self:provider.stage}
    basePath: ''
    certificateArn: arn:aws:acm:us-east-1:517918230755:certificate/a71f6489-08db-4eb5-b86f-30b7104f83f4
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: regional
    apiType: http
  # serverless-frontend-plugin:
  #   distDir: frontend/dist
  #   build:
  #     cwdDir: frontend
  #     command: ['yarn', 'run', 'build']
  #   distribution:
  #     acmCertificateArn: arn:aws:acm:us-east-1:517918230755:certificate/a71f6489-08db-4eb5-b86f-30b7104f83f4
  #     dnsName: thaas.io
  #     altDnsName: www.thaas.io
  #     hostedZoneName: thaas.io.
