org: farkmarnum
app: thaas
service: api

frameworkVersion: '3'

### Lambda + API
provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: backend/handler.handler
    events:
      - httpApi: '*'

### DNS
plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.thaas.io
    basePath: ''
    createRoute53Record: true
